### ISSUE TITLE
メタデータのデータ構造決定

### ISSUE THREAD

**Issue by TETRA2000** [TETRA2000/SoundAnnotate#5]
音声情報と一緒に保存するメタ情報のデータ構造を決定する

**Comment by TETRA2000** [comment]
@shogo-ni こちら、お願いします。
JSONのサンプルデータとかつけて頂けると嬉しいです。

**Comment by shogo-ni** [comment]
音声情報と一緒に保存するメタ情報のデータ構造

~保存するメタ情報

音声ファイル名： .wav
音声ファイル録音日付： YYYY/mm/dd_hh:mm:ss 
音声ファイル録音時間： hh:mm:ss
音声ファイル容量： byte
いびき回数： 回
いびき総時間： hh:mm:ss


~JSON

{					
“filename”:"hoge.wav, “recdate”:"2016/04/01_11:00:00",	“rectime”:"07:50:14", "filesize":"800MB", "snorenum":4, "snoretime":"00:20:40",
}

こんなとこでしょうか？
よろしくお願いします．

**Comment by TETRA2000** [comment]
@shogo-ni 範囲を選択して、コメントを追加するんですよね？
それらの記録に必要な情報もお願いします。

それと、
> 音声ファイル録音日付： YYYY/mm/dd_hh:mm:ss 
音声ファイル録音時間： hh:mm:ss
音声ファイル容量： byte

はファイルから取得できるので不要かと思います

**Comment by shogo-ni** [comment]
@TETRA2000 

アノテーションする内容はいびきだけと考えてました．
般化に向けてアノテーションする内容を”いびき”以外も想定するというご指摘ですよね？

では

いびき回数： 回
いびき総時間： hh:mm:ss
↓
コメント： "hogehoge"
著者： "username"
範囲： "hh:mm:ss"
コメント数： 回
総コメント時間： "hh:mm:ss"

に変更でお願いします．
これで最低限いけるでしょうか？

**Comment by TETRA2000** [comment]
@shogo-ni えっと、範囲には、開始と終了があるのでは？
でないと、この図の情報は保存できない気がします。
https://github.com/TETRA2000/SoundAnnotate/blob/master/SoundAnno.pdf

(ちなみに、般化は想定していませんでした)

**Comment by TETRA2000** [comment]
@shogo-ni その辺対応していただいたら、あとは大丈夫だと思います。
仕様をレポジトリ置いておきたいので、簡単なドキュメントのプルリクください！

終わったらcloseして、 #8 の作業に移ってください！

**Comment by TETRA2000** [comment]
@shogo-ni あ、複数のアノテーションを追加するので、
配列で入れた方がいいですね。

**Comment by shogo-ni** [comment]
@TETRA2000 
なるほど．範囲でそこも表せると思ってました．勉強になります！
では，

コメント： "hogehoge"
著者： "username"
区間範囲： "hh:mm:ss"
区間開始点："hh:mm:ss"
区間終了点："hh:mm:ss"

でいいでしょうか．
配列ですと

{
“comment”:"hogehoge, “username”:"hoge", “range”:"00:10:14", "start":"01:10:49", "finish":01:20:03"
}

これでいいですかね．
仕様も用意していただいてありがとうございます！そちらもやっておきます．
